# Generated by Django 3.2.7 on 2021-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField()),
                ('department', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField(db_column='mobile no')),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
